# Site settings
title: Crayon Eating Monsters
email: thematrimix@yahoo.com
description: A site dedicated to the monsters who eat crayons. Some are ugly or scary and some are not, but they all eat crayons.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://giant-snail.mooo.com" # the base hostname & protocol for your site
twitter_username: thematrimix
github_username:  thematrimix

# Handling Reading
include: [".htaccess"]
exclude: [".vagrant", ".idea", ".sass-cache", "provision", "CNAME", "Vagrantfile", "README.md", "LICENSE", "Notes.txt"]

# Conversion
markdown: kramdown
highlighter: rouge
excerpt_separator: "\n\n"

# Outputting
permalink: pretty
